"""
file_library_ui.py
------------------
Option A : show_file_library()
    Full "📁 File Library" tab — browse, preview, download, delete all
    source and output files, with search/filter controls.

Option B : show_file_picker_inline(key, org_name, object_name)
    Lightweight inline picker rendered inside any upload section.
    Returns (DataFrame, filename) or (None, None).
"""

import streamlit as st
import os
import json
from datetime import datetime

try:
    from .file_store_manager import (
        initialize_db, list_source_files, list_output_files,
        delete_source_file, delete_output_file,
        get_file_stats, scan_and_register_existing,
    )
    from .utils import load_data_file
except ImportError:
    from file_store_manager import (
        initialize_db, list_source_files, list_output_files,
        delete_source_file, delete_output_file,
        get_file_stats, scan_and_register_existing,
    )
    from utils import load_data_file


# ─────────────────────── helpers ────────────────────────────────────────────

def _fmt_size(size_bytes: int) -> str:
    if size_bytes < 1024:
        return f"{size_bytes} B"
    elif size_bytes < 1024 * 1024:
        return f"{size_bytes / 1024:.1f} KB"
    return f"{size_bytes / (1024 * 1024):.1f} MB"


def _fmt_date(iso_str: str) -> str:
    try:
        return datetime.fromisoformat(iso_str).strftime('%Y-%m-%d %H:%M')
    except Exception:
        return iso_str or '—'


def _load_and_preview(file_path: str, file_id_key: str):
    """Render a preview button that expands an inline dataframe."""
    if not os.path.exists(file_path):
        st.warning("⚠️ File not found on disk.")
        return

    preview_key = f"preview_state_{file_id_key}"
    if st.button("👁️ Preview", key=f"btn_prev_{file_id_key}"):
        st.session_state[preview_key] = not st.session_state.get(preview_key, False)

    if st.session_state.get(preview_key, False):
        try:
            if file_path.endswith('.json'):
                with open(file_path) as jf:
                    st.json(json.load(jf))
            else:
                df = load_data_file(file_path)
                if df is not None:
                    st.dataframe(df.head(100), use_container_width=True)
                    st.caption(f"Showing up to 100 rows of {len(df)} total.")
        except Exception as e:
            st.error(f"Cannot preview: {e}")


# ─────────────────────── Option A ───────────────────────────────────────────

def show_file_library():
    """
    Full File Library tab (Option A).
    Call this from the main page router when page == "📁 File Library".
    """
    st.subheader("📁 File Library")
    st.markdown(
        "All source files uploaded to this application and all output files "
        "generated by Validation, Data Loading, and ETL operations are stored "
        "here. Files persist across application restarts."
    )

    # Index existing files on first visit this session
    if not st.session_state.get('_file_library_scanned'):
        with st.spinner("🔍 Indexing existing files on disk…"):
            n = scan_and_register_existing()
        st.session_state['_file_library_scanned'] = True
        if n > 0:
            st.toast(f"Indexed {n} existing file(s) found on disk.", icon="📂")

    # Re-scan button
    col_hdr1, col_hdr2 = st.columns([8, 2])
    with col_hdr2:
        if st.button("🔄 Re-scan disk", use_container_width=True):
            st.session_state.pop('_file_library_scanned', None)
            st.rerun()

    # Stats row
    stats = get_file_stats()
    c1, c2, c3, c4, c5 = st.columns(5)
    c1.metric("Source Files",    stats['source_count'])
    c2.metric("Output Files",    stats['output_count'])
    c3.metric("Source Storage",  f"{stats['source_size_mb']} MB")
    c4.metric("Output Storage",  f"{stats['output_size_mb']} MB")
    c5.metric("Organisations",   stats['org_count'])

    st.divider()

    tab_src, tab_out = st.tabs(["📂 Source Files", "📄 Output Files"])

    with tab_src:
        _show_source_files_tab()

    with tab_out:
        _show_output_files_tab()


def _show_source_files_tab():
    st.markdown("### 📂 Source Files")
    st.caption(
        "Files you have uploaded for Data Loading, Validation, or any other "
        "operation. Use the filters to narrow the list, then preview, download, "
        "or delete individual files."
    )

    # Filters
    col1, col2, col3 = st.columns([3, 3, 1])
    with col1:
        filter_org = st.text_input("Filter by Organisation", key="src_filter_org",
                                   placeholder="e.g. AkashDev")
    with col2:
        filter_obj = st.text_input("Filter by Object", key="src_filter_obj",
                                   placeholder="e.g. Account")
    with col3:
        st.write("")  # spacing
        if st.button("🔄", key="src_tab_refresh", help="Refresh list"):
            st.rerun()

    files = list_source_files(
        org_name=filter_org.strip() or None,
        object_name=filter_obj.strip() or None,
    )

    if not files:
        st.info(
            "No source files stored yet. "
            "Upload a file in **Data Operations** or **Validation** and it will "
            "appear here automatically."
        )
        return

    st.caption(f"{len(files)} file(s) found.")
    st.divider()

    for f in files:
        exists = os.path.exists(f['stored_path'])
        status_badge = "✅" if exists else "⚠️ missing"
        org_obj = f"{f['org_name']} / {f['object_name'] or 'general'}"
        title = (
            f"📄 **{f['original_name']}** &nbsp;·&nbsp; "
            f"{org_obj} &nbsp;·&nbsp; "
            f"{_fmt_date(f['uploaded_at'])} &nbsp; {status_badge}"
        )

        with st.expander(f['original_name'] + f"  [{org_obj}]  {status_badge}",
                         expanded=False):
            m1, m2, m3, m4 = st.columns(4)
            m1.metric("Uploaded",  _fmt_date(f['uploaded_at']))
            m2.metric("Size",      _fmt_size(f['file_size']))
            m3.metric("Rows",      f['row_count'] if f['row_count'] else "—")
            m4.metric("Type",      f['file_type'].upper() if f['file_type'] else "—")

            st.caption(f"📍 `{f['stored_path']}`")

            btn1, btn2, btn3 = st.columns(3)

            with btn1:
                _load_and_preview(f['stored_path'], f"src_{f['id']}")

            with btn2:
                if exists:
                    with open(f['stored_path'], 'rb') as fh:
                        st.download_button(
                            label="📥 Download",
                            data=fh.read(),
                            file_name=f['original_name'],
                            key=f"dl_src_{f['id']}",
                        )

            with btn3:
                if st.button("🗑️ Delete", key=f"del_src_{f['id']}", type="secondary"):
                    delete_source_file(f['id'])
                    st.toast("File deleted.", icon="🗑️")
                    st.rerun()


def _show_output_files_tab():
    st.markdown("### 📄 Output Files")
    st.caption(
        "Files generated by the application — validation reports, invalid-record "
        "exports, data-load results, ETL outputs, and more."
    )

    _OP_TYPES = [
        "All", "GenAI Validation", "Schema Validation",
        "Enhanced Validation", "Validation", "Data Load",
        "ETL", "Mapping", "Object Extraction",
    ]

    col1, col2, col3, col4 = st.columns([3, 3, 3, 1])
    with col1:
        filter_org = st.text_input("Filter by Organisation", key="out_filter_org",
                                   placeholder="e.g. AkashDev")
    with col2:
        filter_obj = st.text_input("Filter by Object", key="out_filter_obj",
                                   placeholder="e.g. Account")
    with col3:
        filter_op = st.selectbox("Filter by Operation", _OP_TYPES, key="out_filter_op")
    with col4:
        st.write("")
        if st.button("🔄", key="out_tab_refresh", help="Refresh list"):
            st.rerun()

    files = list_output_files(
        org_name=filter_org.strip() or None,
        object_name=filter_obj.strip() or None,
        operation_type=filter_op if filter_op != "All" else None,
    )

    if not files:
        st.info(
            "No output files stored yet. "
            "Run a Validation or Data Load operation to generate output files."
        )
        return

    st.caption(f"{len(files)} file(s) found.")
    st.divider()

    _OP_EMOJI = {
        "GenAI Validation":    "🤖",
        "Schema Validation":   "🔍",
        "Enhanced Validation": "⚡",
        "Validation":          "✅",
        "Data Load":           "📥",
        "ETL":                 "🔄",
        "Mapping":             "🗺️",
        "Object Extraction":   "📤",
    }

    for f in files:
        exists = os.path.exists(f['stored_path'])
        status_badge = "✅" if exists else "⚠️ missing"
        org_obj = f"{f['org_name']} / {f['object_name'] or '—'}"
        op_emoji = _OP_EMOJI.get(f['operation_type'], "📄")
        op_label = f['operation_type'] or "Output"

        with st.expander(
            f"{op_emoji} {f['original_name']}  [{org_obj}]  {status_badge}",
            expanded=False,
        ):
            m1, m2, m3, m4 = st.columns(4)
            m1.metric("Generated",  _fmt_date(f['generated_at']))
            m2.metric("Size",       _fmt_size(f['file_size']))
            m3.metric("Rows",       f['row_count'] if f['row_count'] else "—")
            m4.metric("Operation",  op_label)

            if f.get('status'):
                st.caption(f"Status: {f['status']}")
            st.caption(f"📍 `{f['stored_path']}`")

            btn1, btn2, btn3 = st.columns(3)

            with btn1:
                _load_and_preview(f['stored_path'], f"out_{f['id']}")

            with btn2:
                if exists:
                    with open(f['stored_path'], 'rb') as fh:
                        st.download_button(
                            label="📥 Download",
                            data=fh.read(),
                            file_name=f['original_name'],
                            key=f"dl_out_{f['id']}",
                        )

            with btn3:
                if st.button("🗑️ Delete", key=f"del_out_{f['id']}", type="secondary"):
                    delete_output_file(f['id'])
                    st.toast("File deleted.", icon="🗑️")
                    st.rerun()


# ─────────────────────── Option B ───────────────────────────────────────────

def show_file_picker_inline(picker_key: str,
                             org_name: str = None,
                             object_name: str = None):
    """
    Option B — inline stored-file picker.

    Renders a selectbox listing previously stored source files,
    filtered first by (org_name + object_name), then by object_name only,
    then all files if nothing else matches.

    Returns
    -------
    (DataFrame, str)   if the user selects a valid file
    (None, None)       if nothing is selected yet
    """
    # Priority: org + object → object only → all
    files = list_source_files(org_name=org_name, object_name=object_name)
    if not files and object_name:
        files = list_source_files(object_name=object_name)
    if not files:
        files = list_source_files()

    # Filter to files that still exist on disk
    files = [f for f in files if os.path.exists(f['stored_path'])]

    if not files:
        st.info(
            "No stored source files found. "
            "Upload a file first to populate the library."
        )
        return None, None

    options_display = []
    options_map = {}
    for f in files:
        org_obj = f"{f['org_name']} / {f['object_name'] or 'general'}"
        label = (
            f"{f['original_name']}  "
            f"[{org_obj}]  "
            f"— {_fmt_date(f['uploaded_at'])}"
        )
        options_display.append(label)
        options_map[label] = f

    selected_label = st.selectbox(
        "Choose a stored file:",
        options=["— Select a file —"] + options_display,
        key=f"filepicker_{picker_key}",
    )

    if selected_label == "— Select a file —":
        return None, None

    selected = options_map[selected_label]

    try:
        df = load_data_file(selected['stored_path'])
        if df is not None:
            st.success(
                f"✅ Loaded **{selected['original_name']}** "
                f"({len(df):,} rows, {len(df.columns)} columns)"
            )
            return df, selected['original_name']
    except Exception as e:
        st.error(f"Error loading file: {e}")

    return None, None
